server:  
    port: 8080
    servlet: 
       session.timeout: 60000
       contextpath: /yc74ibike    
    undertow:  
        io-threads: 16  
        worker-threads: 256  
        buffer-size: 1024  
        buffers-per-region: 1024  
        direct-buffers: true 
        accesslog: 
            dir: ../log
            enabled: true
            pattern: "%h %l %u %t \"%r\" %s %b %D \"%{i,Referer}\" \"%{i,User-Agent}\""
            prefix: ibike_access
            suffix: .log
            rotate: true
        
logging:
    level: 
        root: info
        org.springframework: info
        com.yc: info
    file: ../log/yc74ibike.log
swagger: 
    enabled: false

