server:
   port: 8002
   
spring:
   application:
      name: cloud-order
      
eureka:
   client:
      serviceUrl:
         defaultZone: http://127.0.0.1:8000/eureka
         
# yum 配置片，使用三个 - 分割
---
spring:
   profiles: order8007
   
server:
   port: 8007
   
---
spring:
   profiles: order8008

server:
   port: 8008

