# yml 文件使用缩进表示层级关系， 缩进必须是用空格符，绝对不能使用制表符 tab \t
# 专业的yml编辑器，会自动的将tab 转成多个空格
# 相同的层级必须由相同的缩进空格
# :   冒号+空格，后面就是配置值

server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/C89-S3-Ply-mybatis
    username: root
    # 配置项之间可以有空行
    password: a
    # yml 支持驼峰命名 + -号分隔符
    driverClassName: com.mysql.jdbc.Driver
    #driver-class-name: com.mysql.jdbc.Driver

mybatis:
  configuration:
  #开启驼峰命名映射
    mapUnderscoreToCamelCase:  true